# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/toughware/open-source/dbgecko

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/toughware/open-source/dbgecko

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/toughware/open-source/dbgecko/CMakeFiles /home/toughware/open-source/dbgecko//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/toughware/open-source/dbgecko/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dbgecko_core

# Build rule for target.
dbgecko_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dbgecko_core
.PHONY : dbgecko_core

# fast build rule for target.
dbgecko_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/build
.PHONY : dbgecko_core/fast

#=============================================================================
# Target rules for targets named dbgecko

# Build rule for target.
dbgecko: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dbgecko
.PHONY : dbgecko

# fast build rule for target.
dbgecko/fast:
	$(MAKE) $(MAKESILENT) -f cmake/CMakeFiles/dbgecko.dir/build.make cmake/CMakeFiles/dbgecko.dir/build
.PHONY : dbgecko/fast

#=============================================================================
# Target rules for targets named test_config_loader

# Build rule for target.
test_config_loader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_config_loader
.PHONY : test_config_loader

# fast build rule for target.
test_config_loader/fast:
	$(MAKE) $(MAKESILENT) -f cmake/tests/CMakeFiles/test_config_loader.dir/build.make cmake/tests/CMakeFiles/test_config_loader.dir/build
.PHONY : test_config_loader/fast

#=============================================================================
# Target rules for targets named test_config_arg_parser

# Build rule for target.
test_config_arg_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_config_arg_parser
.PHONY : test_config_arg_parser

# fast build rule for target.
test_config_arg_parser/fast:
	$(MAKE) $(MAKESILENT) -f cmake/tests/CMakeFiles/test_config_arg_parser.dir/build.make cmake/tests/CMakeFiles/test_config_arg_parser.dir/build
.PHONY : test_config_arg_parser/fast

#=============================================================================
# Target rules for targets named test_list_plugins

# Build rule for target.
test_list_plugins: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_list_plugins
.PHONY : test_list_plugins

# fast build rule for target.
test_list_plugins/fast:
	$(MAKE) $(MAKESILENT) -f cmake/tests/CMakeFiles/test_list_plugins.dir/build.make cmake/tests/CMakeFiles/test_list_plugins.dir/build
.PHONY : test_list_plugins/fast

#=============================================================================
# Target rules for targets named test_plugin_loader

# Build rule for target.
test_plugin_loader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_plugin_loader
.PHONY : test_plugin_loader

# fast build rule for target.
test_plugin_loader/fast:
	$(MAKE) $(MAKESILENT) -f cmake/tests/CMakeFiles/test_plugin_loader.dir/build.make cmake/tests/CMakeFiles/test_plugin_loader.dir/build
.PHONY : test_plugin_loader/fast

#=============================================================================
# Target rules for targets named test_db_backup

# Build rule for target.
test_db_backup: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_db_backup
.PHONY : test_db_backup

# fast build rule for target.
test_db_backup/fast:
	$(MAKE) $(MAKESILENT) -f cmake/tests/CMakeFiles/test_db_backup.dir/build.make cmake/tests/CMakeFiles/test_db_backup.dir/build
.PHONY : test_db_backup/fast

#=============================================================================
# Target rules for targets named test_db_restore

# Build rule for target.
test_db_restore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_db_restore
.PHONY : test_db_restore

# fast build rule for target.
test_db_restore/fast:
	$(MAKE) $(MAKESILENT) -f cmake/tests/CMakeFiles/test_db_restore.dir/build.make cmake/tests/CMakeFiles/test_db_restore.dir/build
.PHONY : test_db_restore/fast

src/000_args.o: src/000_args.c.o
.PHONY : src/000_args.o

# target to build an object file
src/000_args.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/000_args.c.o
.PHONY : src/000_args.c.o

src/000_args.i: src/000_args.c.i
.PHONY : src/000_args.i

# target to preprocess a source file
src/000_args.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/000_args.c.i
.PHONY : src/000_args.c.i

src/000_args.s: src/000_args.c.s
.PHONY : src/000_args.s

# target to generate assembly for a file
src/000_args.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/000_args.c.s
.PHONY : src/000_args.c.s

src/000_config_parser.o: src/000_config_parser.c.o
.PHONY : src/000_config_parser.o

# target to build an object file
src/000_config_parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/000_config_parser.c.o
.PHONY : src/000_config_parser.c.o

src/000_config_parser.i: src/000_config_parser.c.i
.PHONY : src/000_config_parser.i

# target to preprocess a source file
src/000_config_parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/000_config_parser.c.i
.PHONY : src/000_config_parser.c.i

src/000_config_parser.s: src/000_config_parser.c.s
.PHONY : src/000_config_parser.s

# target to generate assembly for a file
src/000_config_parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/000_config_parser.c.s
.PHONY : src/000_config_parser.c.s

src/000_plugin_manager.o: src/000_plugin_manager.c.o
.PHONY : src/000_plugin_manager.o

# target to build an object file
src/000_plugin_manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/000_plugin_manager.c.o
.PHONY : src/000_plugin_manager.c.o

src/000_plugin_manager.i: src/000_plugin_manager.c.i
.PHONY : src/000_plugin_manager.i

# target to preprocess a source file
src/000_plugin_manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/000_plugin_manager.c.i
.PHONY : src/000_plugin_manager.c.i

src/000_plugin_manager.s: src/000_plugin_manager.c.s
.PHONY : src/000_plugin_manager.s

# target to generate assembly for a file
src/000_plugin_manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/000_plugin_manager.c.s
.PHONY : src/000_plugin_manager.c.s

src/000_storage.o: src/000_storage.c.o
.PHONY : src/000_storage.o

# target to build an object file
src/000_storage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/000_storage.c.o
.PHONY : src/000_storage.c.o

src/000_storage.i: src/000_storage.c.i
.PHONY : src/000_storage.i

# target to preprocess a source file
src/000_storage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/000_storage.c.i
.PHONY : src/000_storage.c.i

src/000_storage.s: src/000_storage.c.s
.PHONY : src/000_storage.s

# target to generate assembly for a file
src/000_storage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/000_storage.c.s
.PHONY : src/000_storage.c.s

src/001_config_parser.o: src/001_config_parser.c.o
.PHONY : src/001_config_parser.o

# target to build an object file
src/001_config_parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/001_config_parser.c.o
.PHONY : src/001_config_parser.c.o

src/001_config_parser.i: src/001_config_parser.c.i
.PHONY : src/001_config_parser.i

# target to preprocess a source file
src/001_config_parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/001_config_parser.c.i
.PHONY : src/001_config_parser.c.i

src/001_config_parser.s: src/001_config_parser.c.s
.PHONY : src/001_config_parser.s

# target to generate assembly for a file
src/001_config_parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/001_config_parser.c.s
.PHONY : src/001_config_parser.c.s

src/001_plugin_manager.o: src/001_plugin_manager.c.o
.PHONY : src/001_plugin_manager.o

# target to build an object file
src/001_plugin_manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/001_plugin_manager.c.o
.PHONY : src/001_plugin_manager.c.o

src/001_plugin_manager.i: src/001_plugin_manager.c.i
.PHONY : src/001_plugin_manager.i

# target to preprocess a source file
src/001_plugin_manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/001_plugin_manager.c.i
.PHONY : src/001_plugin_manager.c.i

src/001_plugin_manager.s: src/001_plugin_manager.c.s
.PHONY : src/001_plugin_manager.s

# target to generate assembly for a file
src/001_plugin_manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/001_plugin_manager.c.s
.PHONY : src/001_plugin_manager.c.s

src/001_storage.o: src/001_storage.c.o
.PHONY : src/001_storage.o

# target to build an object file
src/001_storage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/001_storage.c.o
.PHONY : src/001_storage.c.o

src/001_storage.i: src/001_storage.c.i
.PHONY : src/001_storage.i

# target to preprocess a source file
src/001_storage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/001_storage.c.i
.PHONY : src/001_storage.c.i

src/001_storage.s: src/001_storage.c.s
.PHONY : src/001_storage.s

# target to generate assembly for a file
src/001_storage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/001_storage.c.s
.PHONY : src/001_storage.c.s

src/002_config_parser.o: src/002_config_parser.c.o
.PHONY : src/002_config_parser.o

# target to build an object file
src/002_config_parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/002_config_parser.c.o
.PHONY : src/002_config_parser.c.o

src/002_config_parser.i: src/002_config_parser.c.i
.PHONY : src/002_config_parser.i

# target to preprocess a source file
src/002_config_parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/002_config_parser.c.i
.PHONY : src/002_config_parser.c.i

src/002_config_parser.s: src/002_config_parser.c.s
.PHONY : src/002_config_parser.s

# target to generate assembly for a file
src/002_config_parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/002_config_parser.c.s
.PHONY : src/002_config_parser.c.s

src/002_storage.o: src/002_storage.c.o
.PHONY : src/002_storage.o

# target to build an object file
src/002_storage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/002_storage.c.o
.PHONY : src/002_storage.c.o

src/002_storage.i: src/002_storage.c.i
.PHONY : src/002_storage.i

# target to preprocess a source file
src/002_storage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/002_storage.c.i
.PHONY : src/002_storage.c.i

src/002_storage.s: src/002_storage.c.s
.PHONY : src/002_storage.s

# target to generate assembly for a file
src/002_storage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/002_storage.c.s
.PHONY : src/002_storage.c.s

src/003_storage.o: src/003_storage.c.o
.PHONY : src/003_storage.o

# target to build an object file
src/003_storage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/003_storage.c.o
.PHONY : src/003_storage.c.o

src/003_storage.i: src/003_storage.c.i
.PHONY : src/003_storage.i

# target to preprocess a source file
src/003_storage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/003_storage.c.i
.PHONY : src/003_storage.c.i

src/003_storage.s: src/003_storage.c.s
.PHONY : src/003_storage.s

# target to generate assembly for a file
src/003_storage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/003_storage.c.s
.PHONY : src/003_storage.c.s

src/004_storage.o: src/004_storage.c.o
.PHONY : src/004_storage.o

# target to build an object file
src/004_storage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/004_storage.c.o
.PHONY : src/004_storage.c.o

src/004_storage.i: src/004_storage.c.i
.PHONY : src/004_storage.i

# target to preprocess a source file
src/004_storage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/004_storage.c.i
.PHONY : src/004_storage.c.i

src/004_storage.s: src/004_storage.c.s
.PHONY : src/004_storage.s

# target to generate assembly for a file
src/004_storage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/004_storage.c.s
.PHONY : src/004_storage.c.s

src/dbgecko.o: src/dbgecko.c.o
.PHONY : src/dbgecko.o

# target to build an object file
src/dbgecko.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/dbgecko.c.o
.PHONY : src/dbgecko.c.o

src/dbgecko.i: src/dbgecko.c.i
.PHONY : src/dbgecko.i

# target to preprocess a source file
src/dbgecko.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/dbgecko.c.i
.PHONY : src/dbgecko.c.i

src/dbgecko.s: src/dbgecko.c.s
.PHONY : src/dbgecko.s

# target to generate assembly for a file
src/dbgecko.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/dbgecko.c.s
.PHONY : src/dbgecko.c.s

src/utils/000_utils.o: src/utils/000_utils.c.o
.PHONY : src/utils/000_utils.o

# target to build an object file
src/utils/000_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/utils/000_utils.c.o
.PHONY : src/utils/000_utils.c.o

src/utils/000_utils.i: src/utils/000_utils.c.i
.PHONY : src/utils/000_utils.i

# target to preprocess a source file
src/utils/000_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/utils/000_utils.c.i
.PHONY : src/utils/000_utils.c.i

src/utils/000_utils.s: src/utils/000_utils.c.s
.PHONY : src/utils/000_utils.s

# target to generate assembly for a file
src/utils/000_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbgecko_core.dir/build.make CMakeFiles/dbgecko_core.dir/src/utils/000_utils.c.s
.PHONY : src/utils/000_utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... dbgecko"
	@echo "... dbgecko_core"
	@echo "... test_config_arg_parser"
	@echo "... test_config_loader"
	@echo "... test_db_backup"
	@echo "... test_db_restore"
	@echo "... test_list_plugins"
	@echo "... test_plugin_loader"
	@echo "... src/000_args.o"
	@echo "... src/000_args.i"
	@echo "... src/000_args.s"
	@echo "... src/000_config_parser.o"
	@echo "... src/000_config_parser.i"
	@echo "... src/000_config_parser.s"
	@echo "... src/000_plugin_manager.o"
	@echo "... src/000_plugin_manager.i"
	@echo "... src/000_plugin_manager.s"
	@echo "... src/000_storage.o"
	@echo "... src/000_storage.i"
	@echo "... src/000_storage.s"
	@echo "... src/001_config_parser.o"
	@echo "... src/001_config_parser.i"
	@echo "... src/001_config_parser.s"
	@echo "... src/001_plugin_manager.o"
	@echo "... src/001_plugin_manager.i"
	@echo "... src/001_plugin_manager.s"
	@echo "... src/001_storage.o"
	@echo "... src/001_storage.i"
	@echo "... src/001_storage.s"
	@echo "... src/002_config_parser.o"
	@echo "... src/002_config_parser.i"
	@echo "... src/002_config_parser.s"
	@echo "... src/002_storage.o"
	@echo "... src/002_storage.i"
	@echo "... src/002_storage.s"
	@echo "... src/003_storage.o"
	@echo "... src/003_storage.i"
	@echo "... src/003_storage.s"
	@echo "... src/004_storage.o"
	@echo "... src/004_storage.i"
	@echo "... src/004_storage.s"
	@echo "... src/dbgecko.o"
	@echo "... src/dbgecko.i"
	@echo "... src/dbgecko.s"
	@echo "... src/utils/000_utils.o"
	@echo "... src/utils/000_utils.i"
	@echo "... src/utils/000_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

